# Generated by Django 2.1.3 on 2018-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=8)),
                ('student_name', models.CharField(max_length=30)),
                ('student_sex', models.CharField(max_length=1)),
                ('student_college', models.CharField(max_length=15)),
                ('student_class', models.CharField(max_length=10)),
            ],
        ),
    ]
